set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/root/.ciel/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/root/.ciel/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/compute_core"
set ::env(DESIGN_NAME) "compute_core"
set ::env(VERILOG_FILES) "/openlane/designs/compute_core/src/fp16_adder.v /openlane/designs/compute_core/src/fp16_mul.v /openlane/designs/compute_core/src/pe.v /openlane/designs/compute_core/src/skew_buffer.v /openlane/designs/compute_core/src/skew_network.v /openlane/designs/compute_core/src/systolic_array.v /openlane/designs/compute_core/src/compute_core.v"
set ::env(SYNTH_PARAMETERS) "ROWS=4 COLS=4"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "10.0"
set ::env(FP_CORE_UTIL) "40"
set ::env(FP_PDN_CORE_RING) "1"
set ::env(PL_TARGET_DENSITY) "0.45"
set ::env(SYNTH_MAX_FANOUT) "10"
set ::env(ROUTING_CORES) "4"
set ::env(RUN_KLAYOUT) "0"
set ::env(RUN_CVC) "0"
set ::env(MAGIC_DEF_LABELS) "0"
